/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface PoolInterface extends ethers.utils.Interface {
  functions: {
    "DELEGABLE_DOMAIN()": FunctionFragment;
    "DOMAIN_SEPARATOR()": FunctionFragment;
    "PERMIT_TYPEHASH()": FunctionFragment;
    "SIGNATURE_TYPEHASH()": FunctionFragment;
    "addDelegate(address)": FunctionFragment;
    "addDelegateBySignature(address,address,uint256,uint8,bytes32,bytes32)": FunctionFragment;
    "allowance(address,address)": FunctionFragment;
    "approve(address,uint256)": FunctionFragment;
    "balanceOf(address)": FunctionFragment;
    "baseToken()": FunctionFragment;
    "burn(address,address,uint256)": FunctionFragment;
    "burnForBaseToken(address,address,uint256)": FunctionFragment;
    "buyBaseToken(address,address,uint128)": FunctionFragment;
    "buyBaseTokenPreview(uint128)": FunctionFragment;
    "buyFYToken(address,address,uint128)": FunctionFragment;
    "buyFYTokenPreview(uint128)": FunctionFragment;
    "decimals()": FunctionFragment;
    "decreaseAllowance(address,uint256)": FunctionFragment;
    "delegated(address,address)": FunctionFragment;
    "fyToken()": FunctionFragment;
    "g1()": FunctionFragment;
    "g2()": FunctionFragment;
    "getBaseTokenReserves()": FunctionFragment;
    "getFYTokenReserves()": FunctionFragment;
    "increaseAllowance(address,uint256)": FunctionFragment;
    "k()": FunctionFragment;
    "maturity()": FunctionFragment;
    "mint(address,address,uint256)": FunctionFragment;
    "mintWithToken(address,address,uint256)": FunctionFragment;
    "name()": FunctionFragment;
    "nonces(address)": FunctionFragment;
    "permit(address,address,uint256,uint256,uint8,bytes32,bytes32)": FunctionFragment;
    "revokeDelegate(address)": FunctionFragment;
    "sellBaseToken(address,address,uint128)": FunctionFragment;
    "sellBaseTokenPreview(uint128)": FunctionFragment;
    "sellFYToken(address,address,uint128)": FunctionFragment;
    "sellFYTokenPreview(uint128)": FunctionFragment;
    "signatureCount(address)": FunctionFragment;
    "symbol()": FunctionFragment;
    "totalSupply()": FunctionFragment;
    "transfer(address,uint256)": FunctionFragment;
    "transferFrom(address,address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "DELEGABLE_DOMAIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DOMAIN_SEPARATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PERMIT_TYPEHASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SIGNATURE_TYPEHASH",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "addDelegate", values: [string]): string;
  encodeFunctionData(
    functionFragment: "addDelegateBySignature",
    values: [string, string, BigNumberish, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "allowance",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "balanceOf", values: [string]): string;
  encodeFunctionData(functionFragment: "baseToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "burn",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "burnForBaseToken",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buyBaseToken",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buyBaseTokenPreview",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buyFYToken",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buyFYTokenPreview",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "decreaseAllowance",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "delegated",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "fyToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "g1", values?: undefined): string;
  encodeFunctionData(functionFragment: "g2", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getBaseTokenReserves",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFYTokenReserves",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "increaseAllowance",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "k", values?: undefined): string;
  encodeFunctionData(functionFragment: "maturity", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "mint",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintWithToken",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "nonces", values: [string]): string;
  encodeFunctionData(
    functionFragment: "permit",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeDelegate",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "sellBaseToken",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sellBaseTokenPreview",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sellFYToken",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sellFYTokenPreview",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "signatureCount",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [string, string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "DELEGABLE_DOMAIN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DOMAIN_SEPARATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PERMIT_TYPEHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SIGNATURE_TYPEHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addDelegate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addDelegateBySignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "baseToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "burn", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "burnForBaseToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buyBaseToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buyBaseTokenPreview",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buyFYToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "buyFYTokenPreview",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "decreaseAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "delegated", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fyToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "g1", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "g2", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBaseTokenReserves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFYTokenReserves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "increaseAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "k", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "maturity", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "mintWithToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nonces", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "permit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeDelegate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sellBaseToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sellBaseTokenPreview",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sellFYToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sellFYTokenPreview",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "signatureCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;

  events: {
    "Approval(address,address,uint256)": EventFragment;
    "Delegate(address,address,bool)": EventFragment;
    "Liquidity(uint256,address,address,int256,int256,int256)": EventFragment;
    "Trade(uint256,address,address,int256,int256)": EventFragment;
    "Transfer(address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Approval"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Delegate"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Liquidity"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Trade"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Transfer"): EventFragment;
}

export class Pool extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  listeners<T, G>(
    eventFilter?: TypedEventFilter<T, G>
  ): Array<TypedListener<T, G>>;
  off<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  on<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  once<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  removeListener<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  removeAllListeners<T, G>(eventFilter: TypedEventFilter<T, G>): this;

  queryFilter<T, G>(
    event: TypedEventFilter<T, G>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<T & G>>>;

  interface: PoolInterface;

  functions: {
    DELEGABLE_DOMAIN(overrides?: CallOverrides): Promise<[string]>;

    "DELEGABLE_DOMAIN()"(overrides?: CallOverrides): Promise<[string]>;

    DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<[string]>;

    "DOMAIN_SEPARATOR()"(overrides?: CallOverrides): Promise<[string]>;

    PERMIT_TYPEHASH(overrides?: CallOverrides): Promise<[string]>;

    "PERMIT_TYPEHASH()"(overrides?: CallOverrides): Promise<[string]>;

    SIGNATURE_TYPEHASH(overrides?: CallOverrides): Promise<[string]>;

    "SIGNATURE_TYPEHASH()"(overrides?: CallOverrides): Promise<[string]>;

    addDelegate(
      delegate: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "addDelegate(address)"(
      delegate: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    addDelegateBySignature(
      user: string,
      delegate: string,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "addDelegateBySignature(address,address,uint256,uint8,bytes32,bytes32)"(
      user: string,
      delegate: string,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    allowance(
      owner: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "allowance(address,address)"(
      owner: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    approve(
      spender: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "approve(address,uint256)"(
      spender: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    balanceOf(account: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    "balanceOf(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    baseToken(overrides?: CallOverrides): Promise<[string]>;

    "baseToken()"(overrides?: CallOverrides): Promise<[string]>;

    burn(
      from: string,
      to: string,
      tokensBurned: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "burn(address,address,uint256)"(
      from: string,
      to: string,
      tokensBurned: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    burnForBaseToken(
      from: string,
      to: string,
      tokensBurned: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "burnForBaseToken(address,address,uint256)"(
      from: string,
      to: string,
      tokensBurned: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    buyBaseToken(
      from: string,
      to: string,
      tokenOut: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "buyBaseToken(address,address,uint128)"(
      from: string,
      to: string,
      tokenOut: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    buyBaseTokenPreview(
      tokenOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "buyBaseTokenPreview(uint128)"(
      tokenOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    buyFYToken(
      from: string,
      to: string,
      fyTokenOut: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "buyFYToken(address,address,uint128)"(
      from: string,
      to: string,
      fyTokenOut: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    buyFYTokenPreview(
      fyTokenOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "buyFYTokenPreview(uint128)"(
      fyTokenOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    decimals(overrides?: CallOverrides): Promise<[number]>;

    "decimals()"(overrides?: CallOverrides): Promise<[number]>;

    decreaseAllowance(
      spender: string,
      subtractedValue: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "decreaseAllowance(address,uint256)"(
      spender: string,
      subtractedValue: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    delegated(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "delegated(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    fyToken(overrides?: CallOverrides): Promise<[string]>;

    "fyToken()"(overrides?: CallOverrides): Promise<[string]>;

    g1(overrides?: CallOverrides): Promise<[BigNumber]>;

    "g1()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    g2(overrides?: CallOverrides): Promise<[BigNumber]>;

    "g2()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    getBaseTokenReserves(overrides?: CallOverrides): Promise<[BigNumber]>;

    "getBaseTokenReserves()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    getFYTokenReserves(overrides?: CallOverrides): Promise<[BigNumber]>;

    "getFYTokenReserves()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    increaseAllowance(
      spender: string,
      addedValue: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "increaseAllowance(address,uint256)"(
      spender: string,
      addedValue: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    k(overrides?: CallOverrides): Promise<[BigNumber]>;

    "k()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    maturity(overrides?: CallOverrides): Promise<[BigNumber]>;

    "maturity()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    mint(
      from: string,
      to: string,
      tokenOffered: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "mint(address,address,uint256)"(
      from: string,
      to: string,
      tokenOffered: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    mintWithToken(
      from: string,
      to: string,
      fyTokenToBuy: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "mintWithToken(address,address,uint256)"(
      from: string,
      to: string,
      fyTokenToBuy: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    name(overrides?: CallOverrides): Promise<[string]>;

    "name()"(overrides?: CallOverrides): Promise<[string]>;

    nonces(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    "nonces(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    permit(
      owner: string,
      spender: string,
      amount: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "permit(address,address,uint256,uint256,uint8,bytes32,bytes32)"(
      owner: string,
      spender: string,
      amount: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    revokeDelegate(
      delegate: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "revokeDelegate(address)"(
      delegate: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    sellBaseToken(
      from: string,
      to: string,
      baseTokenIn: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "sellBaseToken(address,address,uint128)"(
      from: string,
      to: string,
      baseTokenIn: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    sellBaseTokenPreview(
      baseTokenIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "sellBaseTokenPreview(uint128)"(
      baseTokenIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    sellFYToken(
      from: string,
      to: string,
      fyTokenIn: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "sellFYToken(address,address,uint128)"(
      from: string,
      to: string,
      fyTokenIn: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    sellFYTokenPreview(
      fyTokenIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "sellFYTokenPreview(uint128)"(
      fyTokenIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    signatureCount(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "signatureCount(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    symbol(overrides?: CallOverrides): Promise<[string]>;

    "symbol()"(overrides?: CallOverrides): Promise<[string]>;

    totalSupply(overrides?: CallOverrides): Promise<[BigNumber]>;

    "totalSupply()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    transfer(
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transfer(address,uint256)"(
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    transferFrom(
      sender: string,
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferFrom(address,address,uint256)"(
      sender: string,
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  DELEGABLE_DOMAIN(overrides?: CallOverrides): Promise<string>;

  "DELEGABLE_DOMAIN()"(overrides?: CallOverrides): Promise<string>;

  DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<string>;

  "DOMAIN_SEPARATOR()"(overrides?: CallOverrides): Promise<string>;

  PERMIT_TYPEHASH(overrides?: CallOverrides): Promise<string>;

  "PERMIT_TYPEHASH()"(overrides?: CallOverrides): Promise<string>;

  SIGNATURE_TYPEHASH(overrides?: CallOverrides): Promise<string>;

  "SIGNATURE_TYPEHASH()"(overrides?: CallOverrides): Promise<string>;

  addDelegate(
    delegate: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "addDelegate(address)"(
    delegate: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  addDelegateBySignature(
    user: string,
    delegate: string,
    deadline: BigNumberish,
    v: BigNumberish,
    r: BytesLike,
    s: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "addDelegateBySignature(address,address,uint256,uint8,bytes32,bytes32)"(
    user: string,
    delegate: string,
    deadline: BigNumberish,
    v: BigNumberish,
    r: BytesLike,
    s: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  allowance(
    owner: string,
    spender: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "allowance(address,address)"(
    owner: string,
    spender: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  approve(
    spender: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "approve(address,uint256)"(
    spender: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  balanceOf(account: string, overrides?: CallOverrides): Promise<BigNumber>;

  "balanceOf(address)"(
    account: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  baseToken(overrides?: CallOverrides): Promise<string>;

  "baseToken()"(overrides?: CallOverrides): Promise<string>;

  burn(
    from: string,
    to: string,
    tokensBurned: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "burn(address,address,uint256)"(
    from: string,
    to: string,
    tokensBurned: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  burnForBaseToken(
    from: string,
    to: string,
    tokensBurned: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "burnForBaseToken(address,address,uint256)"(
    from: string,
    to: string,
    tokensBurned: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  buyBaseToken(
    from: string,
    to: string,
    tokenOut: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "buyBaseToken(address,address,uint128)"(
    from: string,
    to: string,
    tokenOut: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  buyBaseTokenPreview(
    tokenOut: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "buyBaseTokenPreview(uint128)"(
    tokenOut: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  buyFYToken(
    from: string,
    to: string,
    fyTokenOut: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "buyFYToken(address,address,uint128)"(
    from: string,
    to: string,
    fyTokenOut: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  buyFYTokenPreview(
    fyTokenOut: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "buyFYTokenPreview(uint128)"(
    fyTokenOut: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  decimals(overrides?: CallOverrides): Promise<number>;

  "decimals()"(overrides?: CallOverrides): Promise<number>;

  decreaseAllowance(
    spender: string,
    subtractedValue: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "decreaseAllowance(address,uint256)"(
    spender: string,
    subtractedValue: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  delegated(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "delegated(address,address)"(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  fyToken(overrides?: CallOverrides): Promise<string>;

  "fyToken()"(overrides?: CallOverrides): Promise<string>;

  g1(overrides?: CallOverrides): Promise<BigNumber>;

  "g1()"(overrides?: CallOverrides): Promise<BigNumber>;

  g2(overrides?: CallOverrides): Promise<BigNumber>;

  "g2()"(overrides?: CallOverrides): Promise<BigNumber>;

  getBaseTokenReserves(overrides?: CallOverrides): Promise<BigNumber>;

  "getBaseTokenReserves()"(overrides?: CallOverrides): Promise<BigNumber>;

  getFYTokenReserves(overrides?: CallOverrides): Promise<BigNumber>;

  "getFYTokenReserves()"(overrides?: CallOverrides): Promise<BigNumber>;

  increaseAllowance(
    spender: string,
    addedValue: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "increaseAllowance(address,uint256)"(
    spender: string,
    addedValue: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  k(overrides?: CallOverrides): Promise<BigNumber>;

  "k()"(overrides?: CallOverrides): Promise<BigNumber>;

  maturity(overrides?: CallOverrides): Promise<BigNumber>;

  "maturity()"(overrides?: CallOverrides): Promise<BigNumber>;

  mint(
    from: string,
    to: string,
    tokenOffered: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "mint(address,address,uint256)"(
    from: string,
    to: string,
    tokenOffered: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  mintWithToken(
    from: string,
    to: string,
    fyTokenToBuy: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "mintWithToken(address,address,uint256)"(
    from: string,
    to: string,
    fyTokenToBuy: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  name(overrides?: CallOverrides): Promise<string>;

  "name()"(overrides?: CallOverrides): Promise<string>;

  nonces(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  "nonces(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  permit(
    owner: string,
    spender: string,
    amount: BigNumberish,
    deadline: BigNumberish,
    v: BigNumberish,
    r: BytesLike,
    s: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "permit(address,address,uint256,uint256,uint8,bytes32,bytes32)"(
    owner: string,
    spender: string,
    amount: BigNumberish,
    deadline: BigNumberish,
    v: BigNumberish,
    r: BytesLike,
    s: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  revokeDelegate(
    delegate: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "revokeDelegate(address)"(
    delegate: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  sellBaseToken(
    from: string,
    to: string,
    baseTokenIn: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "sellBaseToken(address,address,uint128)"(
    from: string,
    to: string,
    baseTokenIn: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  sellBaseTokenPreview(
    baseTokenIn: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "sellBaseTokenPreview(uint128)"(
    baseTokenIn: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  sellFYToken(
    from: string,
    to: string,
    fyTokenIn: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "sellFYToken(address,address,uint128)"(
    from: string,
    to: string,
    fyTokenIn: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  sellFYTokenPreview(
    fyTokenIn: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "sellFYTokenPreview(uint128)"(
    fyTokenIn: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  signatureCount(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  "signatureCount(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  symbol(overrides?: CallOverrides): Promise<string>;

  "symbol()"(overrides?: CallOverrides): Promise<string>;

  totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

  "totalSupply()"(overrides?: CallOverrides): Promise<BigNumber>;

  transfer(
    recipient: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transfer(address,uint256)"(
    recipient: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  transferFrom(
    sender: string,
    recipient: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferFrom(address,address,uint256)"(
    sender: string,
    recipient: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    DELEGABLE_DOMAIN(overrides?: CallOverrides): Promise<string>;

    "DELEGABLE_DOMAIN()"(overrides?: CallOverrides): Promise<string>;

    DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<string>;

    "DOMAIN_SEPARATOR()"(overrides?: CallOverrides): Promise<string>;

    PERMIT_TYPEHASH(overrides?: CallOverrides): Promise<string>;

    "PERMIT_TYPEHASH()"(overrides?: CallOverrides): Promise<string>;

    SIGNATURE_TYPEHASH(overrides?: CallOverrides): Promise<string>;

    "SIGNATURE_TYPEHASH()"(overrides?: CallOverrides): Promise<string>;

    addDelegate(delegate: string, overrides?: CallOverrides): Promise<void>;

    "addDelegate(address)"(
      delegate: string,
      overrides?: CallOverrides
    ): Promise<void>;

    addDelegateBySignature(
      user: string,
      delegate: string,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "addDelegateBySignature(address,address,uint256,uint8,bytes32,bytes32)"(
      user: string,
      delegate: string,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    allowance(
      owner: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "allowance(address,address)"(
      owner: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    approve(
      spender: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "approve(address,uint256)"(
      spender: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    balanceOf(account: string, overrides?: CallOverrides): Promise<BigNumber>;

    "balanceOf(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    baseToken(overrides?: CallOverrides): Promise<string>;

    "baseToken()"(overrides?: CallOverrides): Promise<string>;

    burn(
      from: string,
      to: string,
      tokensBurned: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    "burn(address,address,uint256)"(
      from: string,
      to: string,
      tokensBurned: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    burnForBaseToken(
      from: string,
      to: string,
      tokensBurned: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "burnForBaseToken(address,address,uint256)"(
      from: string,
      to: string,
      tokensBurned: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    buyBaseToken(
      from: string,
      to: string,
      tokenOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "buyBaseToken(address,address,uint128)"(
      from: string,
      to: string,
      tokenOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    buyBaseTokenPreview(
      tokenOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "buyBaseTokenPreview(uint128)"(
      tokenOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    buyFYToken(
      from: string,
      to: string,
      fyTokenOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "buyFYToken(address,address,uint128)"(
      from: string,
      to: string,
      fyTokenOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    buyFYTokenPreview(
      fyTokenOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "buyFYTokenPreview(uint128)"(
      fyTokenOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    decimals(overrides?: CallOverrides): Promise<number>;

    "decimals()"(overrides?: CallOverrides): Promise<number>;

    decreaseAllowance(
      spender: string,
      subtractedValue: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "decreaseAllowance(address,uint256)"(
      spender: string,
      subtractedValue: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    delegated(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "delegated(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    fyToken(overrides?: CallOverrides): Promise<string>;

    "fyToken()"(overrides?: CallOverrides): Promise<string>;

    g1(overrides?: CallOverrides): Promise<BigNumber>;

    "g1()"(overrides?: CallOverrides): Promise<BigNumber>;

    g2(overrides?: CallOverrides): Promise<BigNumber>;

    "g2()"(overrides?: CallOverrides): Promise<BigNumber>;

    getBaseTokenReserves(overrides?: CallOverrides): Promise<BigNumber>;

    "getBaseTokenReserves()"(overrides?: CallOverrides): Promise<BigNumber>;

    getFYTokenReserves(overrides?: CallOverrides): Promise<BigNumber>;

    "getFYTokenReserves()"(overrides?: CallOverrides): Promise<BigNumber>;

    increaseAllowance(
      spender: string,
      addedValue: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "increaseAllowance(address,uint256)"(
      spender: string,
      addedValue: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    k(overrides?: CallOverrides): Promise<BigNumber>;

    "k()"(overrides?: CallOverrides): Promise<BigNumber>;

    maturity(overrides?: CallOverrides): Promise<BigNumber>;

    "maturity()"(overrides?: CallOverrides): Promise<BigNumber>;

    mint(
      from: string,
      to: string,
      tokenOffered: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "mint(address,address,uint256)"(
      from: string,
      to: string,
      tokenOffered: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    mintWithToken(
      from: string,
      to: string,
      fyTokenToBuy: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    "mintWithToken(address,address,uint256)"(
      from: string,
      to: string,
      fyTokenToBuy: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    name(overrides?: CallOverrides): Promise<string>;

    "name()"(overrides?: CallOverrides): Promise<string>;

    nonces(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "nonces(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    permit(
      owner: string,
      spender: string,
      amount: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "permit(address,address,uint256,uint256,uint8,bytes32,bytes32)"(
      owner: string,
      spender: string,
      amount: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    revokeDelegate(delegate: string, overrides?: CallOverrides): Promise<void>;

    "revokeDelegate(address)"(
      delegate: string,
      overrides?: CallOverrides
    ): Promise<void>;

    sellBaseToken(
      from: string,
      to: string,
      baseTokenIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "sellBaseToken(address,address,uint128)"(
      from: string,
      to: string,
      baseTokenIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    sellBaseTokenPreview(
      baseTokenIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "sellBaseTokenPreview(uint128)"(
      baseTokenIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    sellFYToken(
      from: string,
      to: string,
      fyTokenIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "sellFYToken(address,address,uint128)"(
      from: string,
      to: string,
      fyTokenIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    sellFYTokenPreview(
      fyTokenIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "sellFYTokenPreview(uint128)"(
      fyTokenIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    signatureCount(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "signatureCount(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    symbol(overrides?: CallOverrides): Promise<string>;

    "symbol()"(overrides?: CallOverrides): Promise<string>;

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    "totalSupply()"(overrides?: CallOverrides): Promise<BigNumber>;

    transfer(
      recipient: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "transfer(address,uint256)"(
      recipient: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    transferFrom(
      sender: string,
      recipient: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "transferFrom(address,address,uint256)"(
      sender: string,
      recipient: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    Approval(
      owner: string | null,
      spender: string | null,
      value: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { owner: string; spender: string; value: BigNumber }
    >;

    Delegate(
      user: string | null,
      delegate: string | null,
      enabled: null
    ): TypedEventFilter<
      [string, string, boolean],
      { user: string; delegate: string; enabled: boolean }
    >;

    Liquidity(
      maturity: null,
      from: string | null,
      to: string | null,
      daiTokens: null,
      fyDaiTokens: null,
      poolTokens: null
    ): TypedEventFilter<
      [BigNumber, string, string, BigNumber, BigNumber, BigNumber],
      {
        maturity: BigNumber;
        from: string;
        to: string;
        daiTokens: BigNumber;
        fyDaiTokens: BigNumber;
        poolTokens: BigNumber;
      }
    >;

    Trade(
      maturity: null,
      from: string | null,
      to: string | null,
      daiTokens: null,
      fyDaiTokens: null
    ): TypedEventFilter<
      [BigNumber, string, string, BigNumber, BigNumber],
      {
        maturity: BigNumber;
        from: string;
        to: string;
        daiTokens: BigNumber;
        fyDaiTokens: BigNumber;
      }
    >;

    Transfer(
      from: string | null,
      to: string | null,
      value: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { from: string; to: string; value: BigNumber }
    >;
  };

  estimateGas: {
    DELEGABLE_DOMAIN(overrides?: CallOverrides): Promise<BigNumber>;

    "DELEGABLE_DOMAIN()"(overrides?: CallOverrides): Promise<BigNumber>;

    DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<BigNumber>;

    "DOMAIN_SEPARATOR()"(overrides?: CallOverrides): Promise<BigNumber>;

    PERMIT_TYPEHASH(overrides?: CallOverrides): Promise<BigNumber>;

    "PERMIT_TYPEHASH()"(overrides?: CallOverrides): Promise<BigNumber>;

    SIGNATURE_TYPEHASH(overrides?: CallOverrides): Promise<BigNumber>;

    "SIGNATURE_TYPEHASH()"(overrides?: CallOverrides): Promise<BigNumber>;

    addDelegate(delegate: string, overrides?: Overrides): Promise<BigNumber>;

    "addDelegate(address)"(
      delegate: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    addDelegateBySignature(
      user: string,
      delegate: string,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "addDelegateBySignature(address,address,uint256,uint8,bytes32,bytes32)"(
      user: string,
      delegate: string,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    allowance(
      owner: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "allowance(address,address)"(
      owner: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    approve(
      spender: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "approve(address,uint256)"(
      spender: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    balanceOf(account: string, overrides?: CallOverrides): Promise<BigNumber>;

    "balanceOf(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    baseToken(overrides?: CallOverrides): Promise<BigNumber>;

    "baseToken()"(overrides?: CallOverrides): Promise<BigNumber>;

    burn(
      from: string,
      to: string,
      tokensBurned: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "burn(address,address,uint256)"(
      from: string,
      to: string,
      tokensBurned: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    burnForBaseToken(
      from: string,
      to: string,
      tokensBurned: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "burnForBaseToken(address,address,uint256)"(
      from: string,
      to: string,
      tokensBurned: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    buyBaseToken(
      from: string,
      to: string,
      tokenOut: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "buyBaseToken(address,address,uint128)"(
      from: string,
      to: string,
      tokenOut: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    buyBaseTokenPreview(
      tokenOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "buyBaseTokenPreview(uint128)"(
      tokenOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    buyFYToken(
      from: string,
      to: string,
      fyTokenOut: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "buyFYToken(address,address,uint128)"(
      from: string,
      to: string,
      fyTokenOut: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    buyFYTokenPreview(
      fyTokenOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "buyFYTokenPreview(uint128)"(
      fyTokenOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    decimals(overrides?: CallOverrides): Promise<BigNumber>;

    "decimals()"(overrides?: CallOverrides): Promise<BigNumber>;

    decreaseAllowance(
      spender: string,
      subtractedValue: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "decreaseAllowance(address,uint256)"(
      spender: string,
      subtractedValue: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    delegated(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "delegated(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    fyToken(overrides?: CallOverrides): Promise<BigNumber>;

    "fyToken()"(overrides?: CallOverrides): Promise<BigNumber>;

    g1(overrides?: CallOverrides): Promise<BigNumber>;

    "g1()"(overrides?: CallOverrides): Promise<BigNumber>;

    g2(overrides?: CallOverrides): Promise<BigNumber>;

    "g2()"(overrides?: CallOverrides): Promise<BigNumber>;

    getBaseTokenReserves(overrides?: CallOverrides): Promise<BigNumber>;

    "getBaseTokenReserves()"(overrides?: CallOverrides): Promise<BigNumber>;

    getFYTokenReserves(overrides?: CallOverrides): Promise<BigNumber>;

    "getFYTokenReserves()"(overrides?: CallOverrides): Promise<BigNumber>;

    increaseAllowance(
      spender: string,
      addedValue: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "increaseAllowance(address,uint256)"(
      spender: string,
      addedValue: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    k(overrides?: CallOverrides): Promise<BigNumber>;

    "k()"(overrides?: CallOverrides): Promise<BigNumber>;

    maturity(overrides?: CallOverrides): Promise<BigNumber>;

    "maturity()"(overrides?: CallOverrides): Promise<BigNumber>;

    mint(
      from: string,
      to: string,
      tokenOffered: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "mint(address,address,uint256)"(
      from: string,
      to: string,
      tokenOffered: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    mintWithToken(
      from: string,
      to: string,
      fyTokenToBuy: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "mintWithToken(address,address,uint256)"(
      from: string,
      to: string,
      fyTokenToBuy: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    "name()"(overrides?: CallOverrides): Promise<BigNumber>;

    nonces(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "nonces(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    permit(
      owner: string,
      spender: string,
      amount: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "permit(address,address,uint256,uint256,uint8,bytes32,bytes32)"(
      owner: string,
      spender: string,
      amount: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    revokeDelegate(delegate: string, overrides?: Overrides): Promise<BigNumber>;

    "revokeDelegate(address)"(
      delegate: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    sellBaseToken(
      from: string,
      to: string,
      baseTokenIn: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "sellBaseToken(address,address,uint128)"(
      from: string,
      to: string,
      baseTokenIn: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    sellBaseTokenPreview(
      baseTokenIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "sellBaseTokenPreview(uint128)"(
      baseTokenIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    sellFYToken(
      from: string,
      to: string,
      fyTokenIn: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "sellFYToken(address,address,uint128)"(
      from: string,
      to: string,
      fyTokenIn: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    sellFYTokenPreview(
      fyTokenIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "sellFYTokenPreview(uint128)"(
      fyTokenIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    signatureCount(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "signatureCount(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    symbol(overrides?: CallOverrides): Promise<BigNumber>;

    "symbol()"(overrides?: CallOverrides): Promise<BigNumber>;

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    "totalSupply()"(overrides?: CallOverrides): Promise<BigNumber>;

    transfer(
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transfer(address,uint256)"(
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    transferFrom(
      sender: string,
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transferFrom(address,address,uint256)"(
      sender: string,
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    DELEGABLE_DOMAIN(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "DELEGABLE_DOMAIN()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "DOMAIN_SEPARATOR()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    PERMIT_TYPEHASH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "PERMIT_TYPEHASH()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    SIGNATURE_TYPEHASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "SIGNATURE_TYPEHASH()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    addDelegate(
      delegate: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "addDelegate(address)"(
      delegate: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    addDelegateBySignature(
      user: string,
      delegate: string,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "addDelegateBySignature(address,address,uint256,uint8,bytes32,bytes32)"(
      user: string,
      delegate: string,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    allowance(
      owner: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "allowance(address,address)"(
      owner: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    approve(
      spender: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "approve(address,uint256)"(
      spender: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    balanceOf(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "balanceOf(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    baseToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "baseToken()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    burn(
      from: string,
      to: string,
      tokensBurned: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "burn(address,address,uint256)"(
      from: string,
      to: string,
      tokensBurned: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    burnForBaseToken(
      from: string,
      to: string,
      tokensBurned: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "burnForBaseToken(address,address,uint256)"(
      from: string,
      to: string,
      tokensBurned: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    buyBaseToken(
      from: string,
      to: string,
      tokenOut: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "buyBaseToken(address,address,uint128)"(
      from: string,
      to: string,
      tokenOut: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    buyBaseTokenPreview(
      tokenOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "buyBaseTokenPreview(uint128)"(
      tokenOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    buyFYToken(
      from: string,
      to: string,
      fyTokenOut: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "buyFYToken(address,address,uint128)"(
      from: string,
      to: string,
      fyTokenOut: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    buyFYTokenPreview(
      fyTokenOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "buyFYTokenPreview(uint128)"(
      fyTokenOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    decimals(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "decimals()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    decreaseAllowance(
      spender: string,
      subtractedValue: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "decreaseAllowance(address,uint256)"(
      spender: string,
      subtractedValue: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    delegated(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "delegated(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    fyToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "fyToken()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    g1(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "g1()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    g2(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "g2()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getBaseTokenReserves(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getBaseTokenReserves()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFYTokenReserves(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getFYTokenReserves()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    increaseAllowance(
      spender: string,
      addedValue: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "increaseAllowance(address,uint256)"(
      spender: string,
      addedValue: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    k(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "k()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    maturity(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "maturity()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    mint(
      from: string,
      to: string,
      tokenOffered: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "mint(address,address,uint256)"(
      from: string,
      to: string,
      tokenOffered: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    mintWithToken(
      from: string,
      to: string,
      fyTokenToBuy: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "mintWithToken(address,address,uint256)"(
      from: string,
      to: string,
      fyTokenToBuy: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "name()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    nonces(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "nonces(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    permit(
      owner: string,
      spender: string,
      amount: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "permit(address,address,uint256,uint256,uint8,bytes32,bytes32)"(
      owner: string,
      spender: string,
      amount: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    revokeDelegate(
      delegate: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "revokeDelegate(address)"(
      delegate: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    sellBaseToken(
      from: string,
      to: string,
      baseTokenIn: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "sellBaseToken(address,address,uint128)"(
      from: string,
      to: string,
      baseTokenIn: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    sellBaseTokenPreview(
      baseTokenIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "sellBaseTokenPreview(uint128)"(
      baseTokenIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    sellFYToken(
      from: string,
      to: string,
      fyTokenIn: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "sellFYToken(address,address,uint128)"(
      from: string,
      to: string,
      fyTokenIn: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    sellFYTokenPreview(
      fyTokenIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "sellFYTokenPreview(uint128)"(
      fyTokenIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    signatureCount(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "signatureCount(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    symbol(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "symbol()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalSupply(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "totalSupply()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transfer(
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transfer(address,uint256)"(
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    transferFrom(
      sender: string,
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferFrom(address,address,uint256)"(
      sender: string,
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
