/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface YieldMathInterface extends ethers.utils.Interface {
  functions: {
    "MAX()": FunctionFragment;
    "ONE()": FunctionFragment;
    "daiInForFYDaiOut(uint128,uint128,uint128,uint128,int128,int128)": FunctionFragment;
    "daiOutForFYDaiIn(uint128,uint128,uint128,uint128,int128,int128)": FunctionFragment;
    "fyDaiInForDaiOut(uint128,uint128,uint128,uint128,int128,int128)": FunctionFragment;
    "fyDaiOutForDaiIn(uint128,uint128,uint128,uint128,int128,int128)": FunctionFragment;
    "initialReservesValue(uint128,uint128,uint128,int128,int128)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "MAX", values?: undefined): string;
  encodeFunctionData(functionFragment: "ONE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "daiInForFYDaiOut",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "daiOutForFYDaiIn",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "fyDaiInForDaiOut",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "fyDaiOutForDaiIn",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "initialReservesValue",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(functionFragment: "MAX", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ONE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "daiInForFYDaiOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "daiOutForFYDaiIn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fyDaiInForDaiOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fyDaiOutForDaiIn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initialReservesValue",
    data: BytesLike
  ): Result;

  events: {};
}

export class YieldMath extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  listeners<T, G>(
    eventFilter?: TypedEventFilter<T, G>
  ): Array<TypedListener<T, G>>;
  off<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  on<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  once<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  removeListener<T, G>(
    eventFilter: TypedEventFilter<T, G>,
    listener: TypedListener<T, G>
  ): this;
  removeAllListeners<T, G>(eventFilter: TypedEventFilter<T, G>): this;

  queryFilter<T, G>(
    event: TypedEventFilter<T, G>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<T & G>>>;

  interface: YieldMathInterface;

  functions: {
    MAX(overrides?: CallOverrides): Promise<[BigNumber]>;

    "MAX()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    ONE(overrides?: CallOverrides): Promise<[BigNumber]>;

    "ONE()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    daiInForFYDaiOut(
      daiReserves: BigNumberish,
      fyDaiReserves: BigNumberish,
      fyDaiAmount: BigNumberish,
      timeTillMaturity: BigNumberish,
      k: BigNumberish,
      g: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "daiInForFYDaiOut(uint128,uint128,uint128,uint128,int128,int128)"(
      daiReserves: BigNumberish,
      fyDaiReserves: BigNumberish,
      fyDaiAmount: BigNumberish,
      timeTillMaturity: BigNumberish,
      k: BigNumberish,
      g: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    daiOutForFYDaiIn(
      daiReserves: BigNumberish,
      fyDaiReserves: BigNumberish,
      fyDaiAmount: BigNumberish,
      timeTillMaturity: BigNumberish,
      k: BigNumberish,
      g: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "daiOutForFYDaiIn(uint128,uint128,uint128,uint128,int128,int128)"(
      daiReserves: BigNumberish,
      fyDaiReserves: BigNumberish,
      fyDaiAmount: BigNumberish,
      timeTillMaturity: BigNumberish,
      k: BigNumberish,
      g: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    fyDaiInForDaiOut(
      daiReserves: BigNumberish,
      fyDaiReserves: BigNumberish,
      daiAmount: BigNumberish,
      timeTillMaturity: BigNumberish,
      k: BigNumberish,
      g: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "fyDaiInForDaiOut(uint128,uint128,uint128,uint128,int128,int128)"(
      daiReserves: BigNumberish,
      fyDaiReserves: BigNumberish,
      daiAmount: BigNumberish,
      timeTillMaturity: BigNumberish,
      k: BigNumberish,
      g: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    fyDaiOutForDaiIn(
      daiReserves: BigNumberish,
      fyDaiReserves: BigNumberish,
      daiAmount: BigNumberish,
      timeTillMaturity: BigNumberish,
      k: BigNumberish,
      g: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "fyDaiOutForDaiIn(uint128,uint128,uint128,uint128,int128,int128)"(
      daiReserves: BigNumberish,
      fyDaiReserves: BigNumberish,
      daiAmount: BigNumberish,
      timeTillMaturity: BigNumberish,
      k: BigNumberish,
      g: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    initialReservesValue(
      daiReserves: BigNumberish,
      fyDaiReserves: BigNumberish,
      timeTillMaturity: BigNumberish,
      k: BigNumberish,
      c0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "initialReservesValue(uint128,uint128,uint128,int128,int128)"(
      daiReserves: BigNumberish,
      fyDaiReserves: BigNumberish,
      timeTillMaturity: BigNumberish,
      k: BigNumberish,
      c0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  MAX(overrides?: CallOverrides): Promise<BigNumber>;

  "MAX()"(overrides?: CallOverrides): Promise<BigNumber>;

  ONE(overrides?: CallOverrides): Promise<BigNumber>;

  "ONE()"(overrides?: CallOverrides): Promise<BigNumber>;

  daiInForFYDaiOut(
    daiReserves: BigNumberish,
    fyDaiReserves: BigNumberish,
    fyDaiAmount: BigNumberish,
    timeTillMaturity: BigNumberish,
    k: BigNumberish,
    g: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "daiInForFYDaiOut(uint128,uint128,uint128,uint128,int128,int128)"(
    daiReserves: BigNumberish,
    fyDaiReserves: BigNumberish,
    fyDaiAmount: BigNumberish,
    timeTillMaturity: BigNumberish,
    k: BigNumberish,
    g: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  daiOutForFYDaiIn(
    daiReserves: BigNumberish,
    fyDaiReserves: BigNumberish,
    fyDaiAmount: BigNumberish,
    timeTillMaturity: BigNumberish,
    k: BigNumberish,
    g: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "daiOutForFYDaiIn(uint128,uint128,uint128,uint128,int128,int128)"(
    daiReserves: BigNumberish,
    fyDaiReserves: BigNumberish,
    fyDaiAmount: BigNumberish,
    timeTillMaturity: BigNumberish,
    k: BigNumberish,
    g: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  fyDaiInForDaiOut(
    daiReserves: BigNumberish,
    fyDaiReserves: BigNumberish,
    daiAmount: BigNumberish,
    timeTillMaturity: BigNumberish,
    k: BigNumberish,
    g: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "fyDaiInForDaiOut(uint128,uint128,uint128,uint128,int128,int128)"(
    daiReserves: BigNumberish,
    fyDaiReserves: BigNumberish,
    daiAmount: BigNumberish,
    timeTillMaturity: BigNumberish,
    k: BigNumberish,
    g: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  fyDaiOutForDaiIn(
    daiReserves: BigNumberish,
    fyDaiReserves: BigNumberish,
    daiAmount: BigNumberish,
    timeTillMaturity: BigNumberish,
    k: BigNumberish,
    g: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "fyDaiOutForDaiIn(uint128,uint128,uint128,uint128,int128,int128)"(
    daiReserves: BigNumberish,
    fyDaiReserves: BigNumberish,
    daiAmount: BigNumberish,
    timeTillMaturity: BigNumberish,
    k: BigNumberish,
    g: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  initialReservesValue(
    daiReserves: BigNumberish,
    fyDaiReserves: BigNumberish,
    timeTillMaturity: BigNumberish,
    k: BigNumberish,
    c0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "initialReservesValue(uint128,uint128,uint128,int128,int128)"(
    daiReserves: BigNumberish,
    fyDaiReserves: BigNumberish,
    timeTillMaturity: BigNumberish,
    k: BigNumberish,
    c0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    MAX(overrides?: CallOverrides): Promise<BigNumber>;

    "MAX()"(overrides?: CallOverrides): Promise<BigNumber>;

    ONE(overrides?: CallOverrides): Promise<BigNumber>;

    "ONE()"(overrides?: CallOverrides): Promise<BigNumber>;

    daiInForFYDaiOut(
      daiReserves: BigNumberish,
      fyDaiReserves: BigNumberish,
      fyDaiAmount: BigNumberish,
      timeTillMaturity: BigNumberish,
      k: BigNumberish,
      g: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "daiInForFYDaiOut(uint128,uint128,uint128,uint128,int128,int128)"(
      daiReserves: BigNumberish,
      fyDaiReserves: BigNumberish,
      fyDaiAmount: BigNumberish,
      timeTillMaturity: BigNumberish,
      k: BigNumberish,
      g: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    daiOutForFYDaiIn(
      daiReserves: BigNumberish,
      fyDaiReserves: BigNumberish,
      fyDaiAmount: BigNumberish,
      timeTillMaturity: BigNumberish,
      k: BigNumberish,
      g: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "daiOutForFYDaiIn(uint128,uint128,uint128,uint128,int128,int128)"(
      daiReserves: BigNumberish,
      fyDaiReserves: BigNumberish,
      fyDaiAmount: BigNumberish,
      timeTillMaturity: BigNumberish,
      k: BigNumberish,
      g: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    fyDaiInForDaiOut(
      daiReserves: BigNumberish,
      fyDaiReserves: BigNumberish,
      daiAmount: BigNumberish,
      timeTillMaturity: BigNumberish,
      k: BigNumberish,
      g: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "fyDaiInForDaiOut(uint128,uint128,uint128,uint128,int128,int128)"(
      daiReserves: BigNumberish,
      fyDaiReserves: BigNumberish,
      daiAmount: BigNumberish,
      timeTillMaturity: BigNumberish,
      k: BigNumberish,
      g: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    fyDaiOutForDaiIn(
      daiReserves: BigNumberish,
      fyDaiReserves: BigNumberish,
      daiAmount: BigNumberish,
      timeTillMaturity: BigNumberish,
      k: BigNumberish,
      g: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "fyDaiOutForDaiIn(uint128,uint128,uint128,uint128,int128,int128)"(
      daiReserves: BigNumberish,
      fyDaiReserves: BigNumberish,
      daiAmount: BigNumberish,
      timeTillMaturity: BigNumberish,
      k: BigNumberish,
      g: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialReservesValue(
      daiReserves: BigNumberish,
      fyDaiReserves: BigNumberish,
      timeTillMaturity: BigNumberish,
      k: BigNumberish,
      c0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "initialReservesValue(uint128,uint128,uint128,int128,int128)"(
      daiReserves: BigNumberish,
      fyDaiReserves: BigNumberish,
      timeTillMaturity: BigNumberish,
      k: BigNumberish,
      c0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    MAX(overrides?: CallOverrides): Promise<BigNumber>;

    "MAX()"(overrides?: CallOverrides): Promise<BigNumber>;

    ONE(overrides?: CallOverrides): Promise<BigNumber>;

    "ONE()"(overrides?: CallOverrides): Promise<BigNumber>;

    daiInForFYDaiOut(
      daiReserves: BigNumberish,
      fyDaiReserves: BigNumberish,
      fyDaiAmount: BigNumberish,
      timeTillMaturity: BigNumberish,
      k: BigNumberish,
      g: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "daiInForFYDaiOut(uint128,uint128,uint128,uint128,int128,int128)"(
      daiReserves: BigNumberish,
      fyDaiReserves: BigNumberish,
      fyDaiAmount: BigNumberish,
      timeTillMaturity: BigNumberish,
      k: BigNumberish,
      g: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    daiOutForFYDaiIn(
      daiReserves: BigNumberish,
      fyDaiReserves: BigNumberish,
      fyDaiAmount: BigNumberish,
      timeTillMaturity: BigNumberish,
      k: BigNumberish,
      g: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "daiOutForFYDaiIn(uint128,uint128,uint128,uint128,int128,int128)"(
      daiReserves: BigNumberish,
      fyDaiReserves: BigNumberish,
      fyDaiAmount: BigNumberish,
      timeTillMaturity: BigNumberish,
      k: BigNumberish,
      g: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    fyDaiInForDaiOut(
      daiReserves: BigNumberish,
      fyDaiReserves: BigNumberish,
      daiAmount: BigNumberish,
      timeTillMaturity: BigNumberish,
      k: BigNumberish,
      g: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "fyDaiInForDaiOut(uint128,uint128,uint128,uint128,int128,int128)"(
      daiReserves: BigNumberish,
      fyDaiReserves: BigNumberish,
      daiAmount: BigNumberish,
      timeTillMaturity: BigNumberish,
      k: BigNumberish,
      g: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    fyDaiOutForDaiIn(
      daiReserves: BigNumberish,
      fyDaiReserves: BigNumberish,
      daiAmount: BigNumberish,
      timeTillMaturity: BigNumberish,
      k: BigNumberish,
      g: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "fyDaiOutForDaiIn(uint128,uint128,uint128,uint128,int128,int128)"(
      daiReserves: BigNumberish,
      fyDaiReserves: BigNumberish,
      daiAmount: BigNumberish,
      timeTillMaturity: BigNumberish,
      k: BigNumberish,
      g: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialReservesValue(
      daiReserves: BigNumberish,
      fyDaiReserves: BigNumberish,
      timeTillMaturity: BigNumberish,
      k: BigNumberish,
      c0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "initialReservesValue(uint128,uint128,uint128,int128,int128)"(
      daiReserves: BigNumberish,
      fyDaiReserves: BigNumberish,
      timeTillMaturity: BigNumberish,
      k: BigNumberish,
      c0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    MAX(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "MAX()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ONE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "ONE()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    daiInForFYDaiOut(
      daiReserves: BigNumberish,
      fyDaiReserves: BigNumberish,
      fyDaiAmount: BigNumberish,
      timeTillMaturity: BigNumberish,
      k: BigNumberish,
      g: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "daiInForFYDaiOut(uint128,uint128,uint128,uint128,int128,int128)"(
      daiReserves: BigNumberish,
      fyDaiReserves: BigNumberish,
      fyDaiAmount: BigNumberish,
      timeTillMaturity: BigNumberish,
      k: BigNumberish,
      g: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    daiOutForFYDaiIn(
      daiReserves: BigNumberish,
      fyDaiReserves: BigNumberish,
      fyDaiAmount: BigNumberish,
      timeTillMaturity: BigNumberish,
      k: BigNumberish,
      g: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "daiOutForFYDaiIn(uint128,uint128,uint128,uint128,int128,int128)"(
      daiReserves: BigNumberish,
      fyDaiReserves: BigNumberish,
      fyDaiAmount: BigNumberish,
      timeTillMaturity: BigNumberish,
      k: BigNumberish,
      g: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    fyDaiInForDaiOut(
      daiReserves: BigNumberish,
      fyDaiReserves: BigNumberish,
      daiAmount: BigNumberish,
      timeTillMaturity: BigNumberish,
      k: BigNumberish,
      g: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "fyDaiInForDaiOut(uint128,uint128,uint128,uint128,int128,int128)"(
      daiReserves: BigNumberish,
      fyDaiReserves: BigNumberish,
      daiAmount: BigNumberish,
      timeTillMaturity: BigNumberish,
      k: BigNumberish,
      g: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    fyDaiOutForDaiIn(
      daiReserves: BigNumberish,
      fyDaiReserves: BigNumberish,
      daiAmount: BigNumberish,
      timeTillMaturity: BigNumberish,
      k: BigNumberish,
      g: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "fyDaiOutForDaiIn(uint128,uint128,uint128,uint128,int128,int128)"(
      daiReserves: BigNumberish,
      fyDaiReserves: BigNumberish,
      daiAmount: BigNumberish,
      timeTillMaturity: BigNumberish,
      k: BigNumberish,
      g: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialReservesValue(
      daiReserves: BigNumberish,
      fyDaiReserves: BigNumberish,
      timeTillMaturity: BigNumberish,
      k: BigNumberish,
      c0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "initialReservesValue(uint128,uint128,uint128,int128,int128)"(
      daiReserves: BigNumberish,
      fyDaiReserves: BigNumberish,
      timeTillMaturity: BigNumberish,
      k: BigNumberish,
      c0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
